#!/usr/bin/dash
# Switch to the first available profile.
#
# USAGE: auto [{profile-regex} ...]

cd -- "${XDG_CONFIG_HOME:-$HOME/.config}/xrandr"

profiles=$(./list)

for pat; do
  profile=$(printf %s "$profiles" | grep -sm 1 "$pat") &&
  exec ./switch "$profile"
done
return 2
# vim:ft=sh
