#!/usr/bin/dash -eu
# List available profiles.
#
# USAGE: list
#        list {profile} ...

cd -- "${XDG_CONFIG_HOME:-$HOME/.config}/xrandr/profiles.d"

connected=$(
  xrandr -q |
  awk -vORS=' ' '
  "connected" == $2 {
    print $1
  }'
)

awk -vRS='--output[ \t\n]+' \
    -vconnected="$connected" '
!NF {
  P[FILENAME] = 0
}
NF {
  if (index(connected, $1) == 0)
    delete P[FILENAME]
  else if (FILENAME in P)
    ++P[FILENAME]
}
END {
  for (p in P)
    print P[p], p
}' ${@:-*} |
sort -t' ' -nsr |
cut -d' ' -f2-
# vim:ft=sh
