#!/usr/bin/dash -eu
# List available profiles.
#
# USAGE: list
#        list {profile} ...

cd -- "${XDG_CONFIG_HOME:-$HOME/.config}/xrandr/profiles.d"

# treat first output disconnected when lid closed (assume that the first one is
# the builtin)
if grep -sx 'state:\s*close' /proc/acpi/button/lid/*/state; then
  ignore=$(xrandr -q | awk '$2~/connected$/ { print $1; exit }')
fi

# gather connected outputs
connected=$(
  xrandr -q |
  awk -vORS=' ' -vignore="${ignore:-}" '
  "connected" == $2 && ignore != $1 {
    print $1
  }'
)

# list profiles which has all outputs connected
awk -vRS='--output[ \t\n]+' \
    -vconnected="$connected" '
!NF {
  P[FILENAME] = 0
}
NF {
  if (index(connected, $1) == 0)
    delete P[FILENAME]
  else if (FILENAME in P)
    ++P[FILENAME]
}
END {
  for (p in P)
    print P[p], p
}' ${@:-*} |
sort -t' ' -nsr |
cut -d' ' -f2-
# vim:ft=sh
