#!/usr/bin/dash -eu
# Configure outputs.
#
# USAGE: switch {profile}
#        switch {xrandr-args} ...

cd -- "${XDG_CONFIG_HOME:-$HOME/.config}/xrandr"

for f in preswitch.d/*; do
  [ ! -x "$f" ] || "$f"
done

if test $# = 1; then
  profile="$1"
  set -- $(cat "profiles.d/$profile")
  test $# -gt 0
fi

trap 'rm -- "$offcfg" "$usrcfg"' INT TERM EXIT
offcfg=$(mktemp)
usrcfg=$(mktemp)

xrandr -q \
| awk '
$2~/^(dis)?connected$/ {
  print "--output", $1, "--off"
}' \
| sort -k2 >"$offcfg"

echo "${@?Empty configuration}" \
| sed 's/\s--output/\n--output/' \
| sort -k2 >"$usrcfg"

xrandr $(
  join -v 1 -j 2 "$offcfg" "$usrcfg" -o 1.1,1.2,1.3;
  join -j 2      "$offcfg" "$usrcfg" -o 1.1,1.2,2.3,2.4,2.5,2.6,2.7,2.8,2.9;
) || xrandr --auto

for f in postswitch.d/*; do
  [ ! -x "$f" ] || "$f" "${profile:-}"
done
# vi:ft=sh ts=2 sw=2 sts=2 et
