#!/usr/bin/dash -eu
# Configure outputs.
#
# USAGE: switch {profile}
#        switch {xrandr-args} ...

cd -- "${XDG_CONFIG_HOME:-$HOME/.config}/xrandr"

for f in preswitch.d/*; do
  [ ! -x "$f" ] || "$f"
done

if test $# = 1; then
  profile=$1
fi

{
  # switch all output off
  xrandr -q |
  awk '
  $2~/connected$/ {
    printf "--output %s --off\n", $1
  }'

  # read user config
  if test -n "$profile"; then
    cat "profiles.d/$profile"
  else
    printf '%s\n' "$@"
  fi
} |
awk -vRS='--output[ \t\n]+' '
NF {
  O[$1] = $0
}
END {
  for (o in O)
    print "--output " O[o]
}' |
xargs xrandr ||
xrandr --auto

for f in postswitch.d/*; do
  [ ! -x "$f" ] || "$f" "${profile:-}"
done
# vim:ft=sh
